export type TarotCard = {
  id: number;
  name: string;
  arcana: string;
  suit: string | null;
  image: string;
  uprightMeaning: string;
  reversedMeaning: string;
};

export const tarotDeck: TarotCard[] = [
  // Major Arcana (22 cards)
  {
    id: 0,
    name: "The Fool",
    arcana: "major",
    suit: null,
    image: "/images/tarot/fool.jpg",
    uprightMeaning: "New beginnings, innocence, spontaneity, free spirit",
    reversedMeaning: "Recklessness, risk-taking, foolishness, inconsideration",
  },
  {
    id: 1,
    name: "The Magician",
    arcana: "major",
    suit: null,
    image: "/images/tarot/magician.jpg",
    uprightMeaning: "Manifestation, resourcefulness, power, inspired action",
    reversedMeaning: "Manipulation, poor planning, untapped talents",
  },
  {
    id: 2,
    name: "The High Priestess",
    arcana: "major",
    suit: null,
    image: "/images/tarot/high-priestess.jpg",
    uprightMeaning:
      "Intuition, sacred knowledge, divine feminine, subconscious mind",
    reversedMeaning:
      "Secrets, disconnection from intuition, withdrawal, silence",
  },
  {
    id: 3,
    name: "The Empress",
    arcana: "major",
    suit: null,
    image: "/images/tarot/empress.jpg",
    uprightMeaning: "Femininity, beauty, nature, nurturing, abundance",
    reversedMeaning: "Creative block, dependence, emptiness, lack of growth",
  },
  {
    id: 4,
    name: "The Emperor",
    arcana: "major",
    suit: null,
    image: "/images/tarot/emperor.jpg",
    uprightMeaning:
      "Authority, leadership, structure, stability, father figure",
    reversedMeaning: "Domination, excessive control, rigidity, inflexibility",
  },
  {
    id: 5,
    name: "The Hierophant",
    arcana: "major",
    suit: null,
    image: "/images/tarot/hierophant.jpg",
    uprightMeaning: "Spiritual wisdom, tradition, conformity, morality, ethics",
    reversedMeaning: "Personal beliefs, freedom, challenging conventions",
  },
  {
    id: 6,
    name: "The Lovers",
    arcana: "major",
    suit: null,
    image: "/images/tarot/lovers.jpg",
    uprightMeaning: "Love, harmony, relationships, values alignment, choices",
    reversedMeaning: "Self-love, disharmony, imbalance, misalignment of values",
  },
  {
    id: 7,
    name: "The Chariot",
    arcana: "major",
    suit: null,
    image: "/images/tarot/chariot.jpg",
    uprightMeaning: "Control, willpower, success, determination, action",
    reversedMeaning: "Self-discipline, opposition, lack of direction",
  },
  {
    id: 8,
    name: "Strength",
    arcana: "major",
    suit: null,
    image: "/images/tarot/strength.jpg",
    uprightMeaning:
      "Courage, persuasion, influence, compassion, inner strength",
    reversedMeaning:
      "Self-doubt, weakness, insecurity, lack of self-discipline",
  },
  {
    id: 9,
    name: "The Hermit",
    arcana: "major",
    suit: null,
    image: "/images/tarot/hermit.jpg",
    uprightMeaning: "Soul-searching, introspection, solitude, inner guidance",
    reversedMeaning: "Isolation, withdrawal, loneliness, rejection",
  },
  {
    id: 10,
    name: "Wheel of Fortune",
    arcana: "major",
    suit: null,
    image: "/images/tarot/wheel-of-fortune.jpg",
    uprightMeaning: "Good luck, karma, cycles, destiny, turning point",
    reversedMeaning: "Bad luck, resistance to change, breaking cycles",
  },
  {
    id: 11,
    name: "Justice",
    arcana: "major",
    suit: null,
    image: "/images/tarot/justice.jpg",
    uprightMeaning: "Justice, fairness, truth, cause and effect, law",
    reversedMeaning: "Unfairness, lack of accountability, dishonesty",
  },
  {
    id: 12,
    name: "The Hanged Man",
    arcana: "major",
    suit: null,
    image: "/images/tarot/hanged-man.jpg",
    uprightMeaning: "Surrender, letting go, new perspective, enlightenment",
    reversedMeaning: "Resistance, stalling, indecision, delay",
  },
  {
    id: 13,
    name: "Death",
    arcana: "major",
    suit: null,
    image: "/images/tarot/death.jpg",
    uprightMeaning: "Endings, change, transformation, transition",
    reversedMeaning: "Resistance to change, inability to move on, stagnation",
  },
  {
    id: 14,
    name: "Temperance",
    arcana: "major",
    suit: null,
    image: "/images/tarot/temperance.jpg",
    uprightMeaning: "Balance, moderation, patience, purpose, meaning",
    reversedMeaning: "Imbalance, excess, self-healing, realignment",
  },
  {
    id: 15,
    name: "The Devil",
    arcana: "major",
    suit: null,
    image: "/images/tarot/devil.jpg",
    uprightMeaning:
      "Shadow self, attachment, addiction, restriction, sexuality",
    reversedMeaning:
      "Releasing limiting beliefs, exploring dark thoughts, detachment",
  },
  {
    id: 16,
    name: "The Tower",
    arcana: "major",
    suit: null,
    image: "/images/tarot/tower.jpg",
    uprightMeaning: "Sudden change, upheaval, chaos, revelation, awakening",
    reversedMeaning:
      "Personal transformation, fear of change, averting disaster",
  },
  {
    id: 17,
    name: "The Star",
    arcana: "major",
    suit: null,
    image: "/images/tarot/star.jpg",
    uprightMeaning: "Hope, faith, purpose, renewal, spirituality",
    reversedMeaning: "Lack of faith, despair, self-trust, disconnection",
  },
  {
    id: 18,
    name: "The Moon",
    arcana: "major",
    suit: null,
    image: "/images/tarot/moon.jpg",
    uprightMeaning: "Illusion, fear, anxiety, subconscious, intuition",
    reversedMeaning: "Release of fear, repressed emotion, inner confusion",
  },
  {
    id: 19,
    name: "The Sun",
    arcana: "major",
    suit: null,
    image: "/images/tarot/sun.jpg",
    uprightMeaning: "Joy, success, celebration, positivity, vitality",
    reversedMeaning: "Inner child, feeling down, overly optimistic",
  },
  {
    id: 20,
    name: "Judgment",
    arcana: "major",
    suit: null,
    image: "/images/tarot/judgment.jpg",
    uprightMeaning: "Rebirth, inner calling, absolution, self-evaluation",
    reversedMeaning: "Self-doubt, refusal of self-examination, self-loathing",
  },
  {
    id: 21,
    name: "The World",
    arcana: "major",
    suit: null,
    image: "/images/tarot/world.jpg",
    uprightMeaning: "Completion, achievement, fulfillment, sense of belonging",
    reversedMeaning: "Lack of completion, shortcuts, delays",
  },

  // Minor Arcana - Wands (14 cards)
  {
    id: 22,
    name: "Ace of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/ace-of-wands.jpg",
    uprightMeaning:
      "Inspiration, creative spark, new initiative, growth, potential",
    reversedMeaning: "Delays, lack of direction, distractions, low energy",
  },
  {
    id: 23,
    name: "Two of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/two-of-wands.jpg",
    uprightMeaning: "Future planning, progress, decisions, discovery",
    reversedMeaning: "Fear of change, playing it safe, bad planning",
  },
  {
    id: 24,
    name: "Three of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/three-of-wands.jpg",
    uprightMeaning: "Expansion, foresight, overseas opportunities, preparation",
    reversedMeaning: "Lack of foresight, obstacles, delays, frustration",
  },
  {
    id: 25,
    name: "Four of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/four-of-wands.jpg",
    uprightMeaning: "Celebration, harmony, marriage, home, community",
    reversedMeaning: "Lack of support, transience, instability, home conflicts",
  },
  {
    id: 26,
    name: "Five of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/five-of-wands.jpg",
    uprightMeaning: "Competition, conflict, diversity, tension, disagreement",
    reversedMeaning: "Resolution, agreement, harmony, truce",
  },
  {
    id: 27,
    name: "Six of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/six-of-wands.jpg",
    uprightMeaning:
      "Victory, success, public recognition, leadership, achievement",
    reversedMeaning: "Fall from grace, lack of recognition, shamelessness",
  },
  {
    id: 28,
    name: "Seven of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/seven-of-wands.jpg",
    uprightMeaning: "Challenge, competition, protection, perseverance, defense",
    reversedMeaning: "Giving up, overwhelmed, self-doubt, yielding",
  },
  {
    id: 29,
    name: "Eight of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/eight-of-wands.jpg",
    uprightMeaning: "Speed, movement, rapid change, quick decisions, progress",
    reversedMeaning: "Delays, procrastination, slowing down, waiting",
  },
  {
    id: 30,
    name: "Nine of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/nine-of-wands.jpg",
    uprightMeaning:
      "Resilience, courage, persistence, last stand, pushing through",
    reversedMeaning: "Exhaustion, fatigue, giving up, overwhelmed",
  },
  {
    id: 31,
    name: "Ten of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/ten-of-wands.jpg",
    uprightMeaning:
      "Burden, responsibility, hard work, completion, accomplishment",
    reversedMeaning: "Failure to delegate, carrying the burden, overstressed",
  },
  {
    id: 32,
    name: "Page of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/page-of-wands.jpg",
    uprightMeaning:
      "Exploration, enthusiasm, discovery, free spirit, excitement",
    reversedMeaning: "Lack of direction, procrastination, creating conflict",
  },
  {
    id: 33,
    name: "Knight of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/knight-of-wands.jpg",
    uprightMeaning: "Energy, passion, adventure, impulsiveness, action",
    reversedMeaning: "Frustration, scattered energy, delays, burnout",
  },
  {
    id: 34,
    name: "Queen of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/queen-of-wands.jpg",
    uprightMeaning:
      "Courage, confidence, independence, social butterfly, determination",
    reversedMeaning:
      "Self-respect, self-confidence, introverted, re-established",
  },
  {
    id: 35,
    name: "King of Wands",
    arcana: "minor",
    suit: "wands",
    image: "/images/tarot/king-of-wands.jpg",
    uprightMeaning: "Leadership, vision, entrepreneur, honor, big picture",
    reversedMeaning: "Impulsiveness, forceful, domineering, hasty decisions",
  },

  // Minor Arcana - Cups (14 cards)
  {
    id: 36,
    name: "Ace of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/ace-of-cups.jpg",
    uprightMeaning: "New feelings, emotional awakening, intuition, creativity",
    reversedMeaning:
      "Emotional loss, blocked creativity, emptiness, feeling unloved",
  },
  {
    id: 37,
    name: "Two of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/two-of-cups.jpg",
    uprightMeaning:
      "Unity, partnership, connection, mutual attraction, close bonds",
    reversedMeaning:
      "Imbalanced relationship, tension, disconnection, misalignment",
  },
  {
    id: 38,
    name: "Three of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/three-of-cups.jpg",
    uprightMeaning:
      "Celebration, friendship, creativity, collaborations, community",
    reversedMeaning: "Overindulgence, gossip, isolation, loneliness",
  },
  {
    id: 39,
    name: "Four of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/four-of-cups.jpg",
    uprightMeaning: "Apathy, contemplation, disconnectedness, disconnection",
    reversedMeaning: "Sudden awareness, choosing happiness, acceptance",
  },
  {
    id: 40,
    name: "Five of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/five-of-cups.jpg",
    uprightMeaning: "Loss, grief, disappointment, regret, failure, despair",
    reversedMeaning: "Acceptance, moving on, forgiveness, finding peace",
  },
  {
    id: 41,
    name: "Six of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/six-of-cups.jpg",
    uprightMeaning: "Nostalgia, childhood memories, innocence, joy, comfort",
    reversedMeaning: "Living in the past, forgetting the past, naivety",
  },
  {
    id: 42,
    name: "Seven of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/seven-of-cups.jpg",
    uprightMeaning: "Choices, fantasy, illusion, wishful thinking, dreams",
    reversedMeaning: "Clarity, focus, prioritization, avoiding illusions",
  },
  {
    id: 43,
    name: "Eight of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/eight-of-cups.jpg",
    uprightMeaning:
      "Walking away, disillusionment, abandonment, leaving behind",
    reversedMeaning: "Confusion, fear of change, avoidance, fear of loss",
  },
  {
    id: 44,
    name: "Nine of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/nine-of-cups.jpg",
    uprightMeaning: "Contentment, satisfaction, gratitude, wish come true",
    reversedMeaning: "Inner happiness, materialism, dissatisfaction",
  },
  {
    id: 45,
    name: "Ten of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/ten-of-cups.jpg",
    uprightMeaning:
      "Divine love, harmony, alignment, perfect union, family bliss",
    reversedMeaning: "Broken family, domestic conflict, disharmony",
  },
  {
    id: 46,
    name: "Page of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/page-of-cups.jpg",
    uprightMeaning:
      "Creative opportunities, intuitive messages, curiosity, possibility",
    reversedMeaning: "Creative blocks, emotional immaturity, escapism",
  },
  {
    id: 47,
    name: "Knight of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/knight-of-cups.jpg",
    uprightMeaning:
      "Following your heart, romantic, idealistic, artistic, invitation",
    reversedMeaning: "Moodiness, emotional manipulation, unrealistic",
  },
  {
    id: 48,
    name: "Queen of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/queen-of-cups.jpg",
    uprightMeaning: "Compassion, calm, comfort, emotional security, intuition",
    reversedMeaning: "Emotional insecurity, co-dependency, self-care",
  },
  {
    id: 49,
    name: "King of Cups",
    arcana: "minor",
    suit: "cups",
    image: "/images/tarot/king-of-cups.jpg",
    uprightMeaning: "Emotional balance, compassion, control, diplomatic",
    reversedMeaning: "Emotional manipulation, coldness, moodiness",
  },

  // Minor Arcana - Swords (14 cards)
  {
    id: 50,
    name: "Ace of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/ace-of-swords.jpg",
    uprightMeaning: "Breakthrough, clarity, sharp mind, truth, mental power",
    reversedMeaning: "Confusion, brutality, chaos, mental fog, lies",
  },
  {
    id: 51,
    name: "Two of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/two-of-swords.jpg",
    uprightMeaning: "Difficult choices, stalemate, denial, stuck in the middle",
    reversedMeaning: "Indecision, confusion, information overload",
  },
  {
    id: 52,
    name: "Three of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/three-of-swords.jpg",
    uprightMeaning: "Heartbreak, emotional pain, grief, sorrow, trauma",
    reversedMeaning: "Recovery, releasing pain, forgiveness, moving on",
  },
  {
    id: 53,
    name: "Four of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/four-of-swords.jpg",
    uprightMeaning: "Rest, restoration, contemplation, recuperation, sanctuary",
    reversedMeaning: "Exhaustion, burnout, stagnation, delayed healing",
  },
  {
    id: 54,
    name: "Five of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/five-of-swords.jpg",
    uprightMeaning: "Conflict, tension, defeat, win at all costs, hostility",
    reversedMeaning: "Reconciliation, making amends, past resentment",
  },
  {
    id: 55,
    name: "Six of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/six-of-swords.jpg",
    uprightMeaning: "Transition, moving on, calmer waters, healing, release",
    reversedMeaning: "Baggage, unresolved issues, resisting transition",
  },
  {
    id: 56,
    name: "Seven of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/seven-of-swords.jpg",
    uprightMeaning: "Deception, trickery, tactics, self-deceit, strategy",
    reversedMeaning: "Secrets revealed, imposter syndrome, coming clean",
  },
  {
    id: 57,
    name: "Eight of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/eight-of-swords.jpg",
    uprightMeaning:
      "Imprisonment, entrapment, self-limiting beliefs, isolation",
    reversedMeaning: "Self-acceptance, new perspective, freedom, self-belief",
  },
  {
    id: 58,
    name: "Nine of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/nine-of-swords.jpg",
    uprightMeaning: "Anxiety, worry, fear, depression, nightmares, distress",
    reversedMeaning: "Inner turmoil, secrets, burden, transformation",
  },
  {
    id: 59,
    name: "Ten of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/ten-of-swords.jpg",
    uprightMeaning: "Painful endings, betrayal, loss, crisis, rock bottom",
    reversedMeaning:
      "Recovery, regeneration, inevitable ending, processing grief",
  },
  {
    id: 60,
    name: "Page of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/page-of-swords.jpg",
    uprightMeaning:
      "New ideas, curiosity, intellectual appetite, thirst for knowledge",
    reversedMeaning: "Self-expression, all talk and no action, haste",
  },
  {
    id: 61,
    name: "Knight of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/knight-of-swords.jpg",
    uprightMeaning: "Action, ambition, thriving on challenge, determined",
    reversedMeaning: "Impulsiveness, no direction, unpredictability",
  },
  {
    id: 62,
    name: "Queen of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/queen-of-swords.jpg",
    uprightMeaning: "Independent, unbiased judgment, clear boundaries, direct",
    reversedMeaning: "Overly emotional, cold-hearted, bitter, cruel",
  },
  {
    id: 63,
    name: "King of Swords",
    arcana: "minor",
    suit: "swords",
    image: "/images/tarot/king-of-swords.jpg",
    uprightMeaning: "Mental clarity, intellectual power, authority, truth",
    reversedMeaning: "Quiet power, inner truth, misuse of power, manipulation",
  },

  // Minor Arcana - Pentacles (14 cards)
  {
    id: 64,
    name: "Ace of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/ace-of-pentacles.jpg",
    uprightMeaning:
      "New financial opportunity, prosperity, abundance, security",
    reversedMeaning: "Lost opportunity, lack of planning, bad investment",
  },
  {
    id: 65,
    name: "Two of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/two-of-pentacles.jpg",
    uprightMeaning:
      "Balancing resources, priorities, adaptability, flexibility",
    reversedMeaning: "Imbalance, disorganization, overwhelmed",
  },
  {
    id: 66,
    name: "Three of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/three-of-pentacles.jpg",
    uprightMeaning: "Teamwork, collaboration, learning, implementation",
    reversedMeaning: "Lack of teamwork, disorganized, lack of skill",
  },
  {
    id: 67,
    name: "Four of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/four-of-pentacles.jpg",
    uprightMeaning:
      "Conservation, security, frugality, boundaries, saving money",
    reversedMeaning: "Greed, materialism, possessiveness, blocked change",
  },
  {
    id: 68,
    name: "Five of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/five-of-pentacles.jpg",
    uprightMeaning: "Financial loss, poverty, isolation, worry, insecurity",
    reversedMeaning: "Recovery, spiritual poverty, asking for help",
  },
  {
    id: 69,
    name: "Six of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/six-of-pentacles.jpg",
    uprightMeaning: "Generosity, charity, giving, receiving, gratitude",
    reversedMeaning: "Strings attached, power dynamics, insincere gifts",
  },
  {
    id: 70,
    name: "Seven of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/seven-of-pentacles.jpg",
    uprightMeaning:
      "Long-term success, perseverance, sustainable results, patience",
    reversedMeaning: "Lack of progress, procrastination, impatience",
  },
  {
    id: 71,
    name: "Eight of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/eight-of-pentacles.jpg",
    uprightMeaning: "Apprenticeship, mastery, skill development, diligence",
    reversedMeaning: "Perfectionism, lack of ambition, uninspiring work",
  },
  {
    id: 72,
    name: "Nine of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/nine-of-pentacles.jpg",
    uprightMeaning:
      "Luxury, self-sufficiency, financial independence, prosperity",
    reversedMeaning: "Superficiality, materialism, compromise, false success",
  },
  {
    id: 73,
    name: "Ten of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/ten-of-pentacles.jpg",
    uprightMeaning: "Legacy, inheritance, family, establishment, wealth",
    reversedMeaning:
      "Family disputes, bankruptcy, loss of home, family illusions",
  },
  {
    id: 74,
    name: "Page of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/page-of-pentacles.jpg",
    uprightMeaning:
      "Manifestation, financial opportunity, student, scholarship",
    reversedMeaning: "Lack of progress, procrastination, missed opportunity",
  },
  {
    id: 75,
    name: "Knight of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/knight-of-pentacles.jpg",
    uprightMeaning:
      "Hard work, productivity, responsibility, routine, conservatism",
    reversedMeaning: "Boredom, feeling stuck, perfectionism, obsessiveness",
  },
  {
    id: 76,
    name: "Queen of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/queen-of-pentacles.jpg",
    uprightMeaning: "Nurturing, practical, provider, abundance, security",
    reversedMeaning: "Codependency, insecurity, materialistic, worrying",
  },
  {
    id: 77,
    name: "King of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "/images/tarot/king-of-pentacles.jpg",
    uprightMeaning: "Abundance, prosperity, security, discipline, wealth",
    reversedMeaning: "Materialism, poor financial decisions, greed",
  },
];
